name: Build AppImage

on:
  push:
    branches: [ appimage ]
jobs:
  build-appimage:
    runs-on: ubuntu-latest
    steps:
      - name: Install code
        uses: actions/checkout@v2
      - name: Build AppImage
        uses: AppImageCrafters/build-appimage@v1
        with:
          recipe: AppImageBuilder.yml
