- name: Build AppImage

  on:
    push:
      branches: [ appimage ]
  jobs:
    build-appimage:
      runs-on: ubuntu-latest
      steps:
        - name: Build AppImage
          uses: AppImageCrafters/build-appimage@v1
          with:
            recipe: AppImageBuilder.yml
